-- 코드를 입력하세요
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES
FROM REST_INFO t1
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO t2
    WHERE t1.FOOD_TYPE = t2.FOOD_TYPE
    )
ORDER BY FOOD_TYPE DESC;