-- 코드를 입력하세요
SELECT USED_GOODS_USER.USER_ID
     , USED_GOODS_USER.NICKNAME
     , CONCAT(USED_GOODS_USER.CITY, " ", USED_GOODS_USER.STREET_ADDRESS1, " ", USED_GOODS_USER.STREET_ADDRESS2) AS "전체주소"
     , CONCAT(SUBSTRING(USED_GOODS_USER.TLNO, 1, 3), '-', SUBSTRING(USED_GOODS_USER.TLNO, 4, 4), '-', SUBSTRING(USED_GOODS_USER.TLNO, 8)) AS "전화번호"
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
GROUP BY USED_GOODS_USER.USER_ID
HAVING COUNT(*) >= 3
ORDER BY USED_GOODS_USER.USER_ID DESC