-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H') AS 'HOUR',
       COUNT(*) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME, '%H') >= '09'
      AND DATE_FORMAT(DATETIME, '%H') < '20'
GROUP BY 1
ORDER BY 1 ASC