-- 코드를 입력하세요
SELECT DISTINCT(CAR_RENTAL_COMPANY_CAR.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '세단'
      AND DATE_FORMAT(CAR_RENTAL_COMPANY_RENTAL_HISTORY.start_date,'%Y-%m') = '2022-10'
ORDER BY CAR_RENTAL_COMPANY_CAR.CAR_ID DESC