-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID ,'/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD
JOIN USED_GOODS_FILE ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_FILE.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS)
       FROM USED_GOODS_BOARD)
ORDER BY USED_GOODS_FILE.FILE_ID DESC