-- 코드를 입력하세요
SELECT MEMBER_ID,
       MEMBER_NAME,
       GENDER, 
       DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE MONTHNAME(DATE_OF_BIRTH) = 'March'
      AND TLNO IS NOT NULL
      AND GENDER = 'W'
ORDER BY MEMBER_ID